[custom]
ruleset=🌎 代理出口,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/dns.list
ruleset=🌎 代理出口,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/google-proxy.list
ruleset=🌎 代理出口,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/private.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 直连出口,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/incorrect_ads.list
ruleset=⛔️ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=⛔️ 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=⛔️ 广告拦截,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/ban.list
ruleset=⛔️ 广告拦截,https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo_surge.list
ruleset=🏦 证券投资,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/broker.list
ruleset=🎯 直连出口,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/cn.list
ruleset=🇭🇰 香港节点,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/hk.list
ruleset=💰 加密货币,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Crypto.list
ruleset=✨ 人工智能,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/ai.list
ruleset=🌎 代理出口,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🌎 代理出口,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌎 代理出口,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/proxy.list
ruleset=🌎 代理出口,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Porn.list
ruleset=🪟 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🔬 回校代理,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/academic.list
ruleset=DIRECT,[]DOMAIN-SUFFIX,ustc.edu.cn
ruleset=DIRECT,https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/DMCA-Sensitive.list
ruleset=DIRECT,https://raw.githubusercontent.com/jtzhpf/USTC-rules/main/loongson.list
ruleset=✈️ 电报信息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🎯 直连出口,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🌎 代理出口`select`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=🎯 直连出口`select`[]DIRECT`(^(?=.*(?:CN-USTC)).*)`
custom_proxy_group=✨ 人工智能`select`[]🌎 代理出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=🪟 微软服务`select`[]🌎 代理出口`[]🎯 直连出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=🍎 苹果服务`select`[]🎯 直连出口`[]🌎 代理出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=✈️ 电报信息`select`[]🌎 代理出口`[]💫 任播出口`[]🎯 直连出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=🏦 证券投资`select`[]🎯 直连出口`[]🌎 代理出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=💰 加密货币`select`(^(?=.*(?:HK-USTC)).*)`[]🌎 代理出口`[]🎯 直连出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=🔬 回校代理`select`(^(?=.*(?:CN-USTC)).*)`[]🎯 直连出口`[]🌎 代理出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`
custom_proxy_group=🐟 漏网之鱼`select`[]🌎 代理出口`[]🎯 直连出口`[]🔯 美国故障转移`[]🔯 日本故障转移`[]♻️ 美国自动`[]♻️ 日本自动`[]⚖️ 美国均衡`[]⚖️ 日本均衡`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇪🇺 欧盟节点`[]🚀 手动选择`

# 地区基础节点组
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇺🇲 美国节点`select`(^(?!.*(CN-USTC|HK-USTC|EU-USTC)).*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*$)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`select`(日|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|Tokyo|Osaka)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇪🇺 欧盟节点`select`(EU)`http://www.gstatic.com/generate_204`300,,50

# 其他通用组
custom_proxy_group=🚀 手动选择`select`(^(?!.*(CN-USTC|直连)).*)
custom_proxy_group=⛔️ 广告拦截`select`[]REJECT`[]🌎 代理出口`[]🎯 直连出口`[]💫 任播出口`
custom_proxy_group=💫 任播出口`load-balance`round-robin`(任播节点)`http://www.gstatic.com/generate_204`300,,50

# 美国自动化套件
custom_proxy_group=⚖️ 美国均衡`load-balance`consistent-hashing`(^(?!.*(CN-USTC|HK-USTC|EU-USTC|US-USTC)).*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*$)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 美国自动`url-test`(^(?!.*(CN-USTC|HK-USTC|EU-USTC|US-USTC)).*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*$)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 美国故障转移`fallback`(^(?!.*(CN-USTC|HK-USTC|EU-USTC|US-USTC)).*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*$)`http://www.gstatic.com/generate_204`300,,50

# 日本自动化套件
custom_proxy_group=⚖️ 日本均衡`load-balance`consistent-hashing`(日|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|Tokyo|Osaka)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 日本自动`url-test`(日|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|Tokyo|Osaka)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 日本故障转移`fallback`(日|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|Tokyo|Osaka)`http://www.gstatic.com/generate_204`300,,50

#{% if request.target == "clash" or request.target == "clashr" %}
#custom_proxy_group=📡 CN-USTC_1中转`relay`CN-USTC_1`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#custom_proxy_group=📡 CN-USTC_2中转`relay`CN-USTC_2`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#custom_proxy_group=📡 HK-USTC_1中转`relay`HK-USTC_1`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#custom_proxy_group=📡 HK-USTC_2中转`relay`HK-USTC_2`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#custom_proxy_group=📡 USTC-US_1中转`relay`USTC-US_1`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#custom_proxy_group=📡 USTC-US_2中转`relay`USTC-US_2`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#custom_proxy_group=📡 USTC-US_3中转`relay`USTC-US_3`(^cdn$)`http://www.gstatic.com/generate_204`300,10,50
#{% endif %}
enable_rule_generator=true
overwrite_original_rules=true
clash.dns=1
